---
title: "p8105_hw2_bsr2136"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## Problem 0

```{r problem 0, warning=FALSE}
dir.create("files_for_hw2")
```

## Problem 1

```{r problem 1a, results=FALSE}
trash_wheel <- 
  read_excel("./files_for_hw2/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             range = "A2:N408", sheet = "Mr. Trash Wheel")

trash_wheel <- trash_wheel %>% 
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>%
  mutate(sports_balls = as.integer(round(sports_balls,0)))
  
prec_2018 <- read_excel("./files_for_hw2/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             range = "A3:B14", sheet = "2018 Precipitation",
             col_names = c("month","precipitation_inches"))

prec_2017 <- read_excel("./files_for_hw2/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
             range = "A3:B14", sheet = "2017 Precipitation",
             col_names = c("month","precipitation_inches"))

prec_2018 <- prec_2018 %>%
  filter(!is.na(precipitation_inches)) %>%
  mutate(year = 2018)

prec_2017 <- prec_2017 %>%
  filter(!is.na(precipitation_inches)) %>%
  mutate(year = 2017)

precipitation_2017_2018 <- bind_rows(prec_2017,prec_2018) %>%
  mutate(month = month.name[month])
```

```{r Problem 1b}
## The number of observations in the Mr. Trash Wheel sheet is
nrow(trash_wheel)
## The variable dumpster gives a number from 1-285 that identifies which dumpster the data is referencing.
## The variables month, year, and date give information on the date of trash collection by Mr. Trash wheel, which ranges from May 2015 to June 2019.
## The variables weight_tons and volume_cubic_yards give information on how much trash was collected.
```

```{r Problem 1c}
## The number of observations in the combined precipitation dataset is
nrow(precipitation_2017_2018)
## The variable precipitation_inches gives the amount of precipitation in inches.
## The variables month and year give information on the date that precipitation fell in, and ranges from January 2017 to December 2018.
```

```{r Problem 1d}
## The total amount of rainfall in 2018 (for available data) was
precipitation_2017_2018 %>%
  filter(year==2018) %>%
  summarize(total_prec = sum(precipitation_inches))

## The median number of sports balls in a dumpster in 2017 was
trash_wheel %>%
  filter(year==2017) %>%
  summarize(median_sports_balls = median(sports_balls))
```


## Problem 2


```{r problem 2a, results = FALSE}
pols <- read_csv("./files_for_hw2/pols-month.csv")

unemploy <- read_csv("./files_for_hw2/unemployment.csv")

snp <- read_csv("./files_for_hw2/snp.csv")

pols <- pols %>%
  separate(mon, into = c("year","month","day"), sep = "-") %>%
  mutate(month = month.name[as.integer(month)],
         president = ifelse(prez_gop>=1,"gop",ifelse(prez_dem>=1,"dem",NA))
                            ) %>%
  select(year,month,president,everything(),-prez_gop,-prez_dem,-day)

snp <- snp %>%
  separate(date, into = c("month","day","year"), sep = "/") %>%
  mutate(month = month.name[as.integer(month)]) %>%
  select(year,month,close)

test <- unemploy %>%
  rename('1' = Jan,
         '2' = Feb,
         '3' = Mar,
         '4' = Apr,
         '5' = May,
         '6' = Jun,
         '7' = Jul,
         '8' = Aug,
         '9' = Sep,
         '10' = Oct,
         '11' = Nov,
         '12' = Dec) %>%
  pivot_longer(2:13, 
               names_to = "month",
               values_to = "unemploy_rate") %>%
  mutate(month = month.name[as.integer(month)])

```


## Problem 3

```{r}

```

